version: "3.9"
services:
  app:
    build: ./docker/
    container_name: app
    ports:
      - "9000"
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - "80:80"
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: lara_bloug
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
